"""engineering_metrics: initial tables

Revision ID: 4cf19edf0dc6
Revises: 
Create Date: 2026-07-07 15:48:59.336472

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4cf19edf0dc6'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('engineering_metrics',)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ci_run_projection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('ci_run_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository', 'ci_run_id'),
    schema='engineering_metrics'
    )
    op.create_table('pr_lifecycle_projection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merged', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository', 'pr_number'),
    schema='engineering_metrics'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pr_lifecycle_projection', schema='engineering_metrics')
    op.drop_table('ci_run_projection', schema='engineering_metrics')
    # ### end Alembic commands ###
