"""test_intelligence: add file_coverage_signal (Coverage Intelligence)

Revision ID: 53d5214a6e96
Revises: 65dc20c1265d
Create Date: 2026-07-02 17:07:13.954876

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53d5214a6e96'
down_revision: str | Sequence[str] | None = '65dc20c1265d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_coverage_signal',
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('lines_covered', sa.Integer(), nullable=False),
    sa.Column('lines_total', sa.Integer(), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('file_path', 'repository'),
    schema='test_intelligence'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_coverage_signal', schema='test_intelligence')
    # ### end Alembic commands ###
