"""test_intelligence: add test_duration_signal (CI/CD Optimization)

Revision ID: 65dc20c1265d
Revises: df8843a6a586
Create Date: 2026-07-02 16:37:36.927130

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '65dc20c1265d'
down_revision: str | Sequence[str] | None = 'df8843a6a586'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_duration_signal',
    sa.Column('test_identifier', sa.String(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('median_duration_ms', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('test_identifier', 'repository'),
    schema='test_intelligence'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_duration_signal', schema='test_intelligence')
    # ### end Alembic commands ###
