"""test_intelligence: initial tables

Revision ID: df8843a6a586
Revises: 
Create Date: 2026-07-02 14:27:20.454226

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'df8843a6a586'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('test_intelligence',)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='test_intelligence'
    )
    op.create_table('pr_changed_files_projection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('changed_file_paths', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository', 'commit_sha'),
    schema='test_intelligence'
    )
    op.create_table('test_impact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='test_intelligence'
    )
    op.create_table('test_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('ci_run_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository', 'commit_sha'),
    schema='test_intelligence'
    )
    op.create_table('test_stability_signal',
    sa.Column('test_identifier', sa.String(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('flakiness_score', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('test_identifier', 'repository'),
    schema='test_intelligence'
    )
    op.create_table('test_case_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_run_id', sa.UUID(), nullable=False),
    sa.Column('test_identifier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('failure_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_intelligence.test_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_intelligence'
    )
    op.create_table('test_impact_affected_test',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_impact_id', sa.UUID(), nullable=False),
    sa.Column('test_identifier', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['test_impact_id'], ['test_intelligence.test_impact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='test_intelligence'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_impact_affected_test', schema='test_intelligence')
    op.drop_table('test_case_result', schema='test_intelligence')
    op.drop_table('test_stability_signal', schema='test_intelligence')
    op.drop_table('test_run', schema='test_intelligence')
    op.drop_table('test_impact', schema='test_intelligence')
    op.drop_table('pr_changed_files_projection', schema='test_intelligence')
    op.drop_table('outbox_event', schema='test_intelligence')
    # ### end Alembic commands ###
