"""dependency_analysis: initial tables

Revision ID: 9a63c60bce29
Revises: 
Create Date: 2026-07-02 17:36:06.080585

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a63c60bce29'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('dependency_analysis',)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_manifest_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('ecosystem', sa.String(), nullable=False),
    sa.Column('packages', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository', 'commit_sha', 'ecosystem'),
    schema='dependency_analysis'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependency_manifest_snapshot', schema='dependency_analysis')
    # ### end Alembic commands ###
