"""pr_analysis add llm token and latency tracking

Revision ID: 9b0b976f360a
Revises: d3a90afebafe
Create Date: 2026-07-07 11:52:21.816484

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9b0b976f360a'
down_revision: str | Sequence[str] | None = 'd3a90afebafe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'pr_risk_assessment',
        sa.Column('llm_tokens_used', sa.Integer(), nullable=False),
        schema='pr_analysis',
    )
    op.add_column(
        'pr_risk_assessment',
        sa.Column('llm_latency_ms', sa.Integer(), nullable=False),
        schema='pr_analysis',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pr_risk_assessment', 'llm_latency_ms', schema='pr_analysis')
    op.drop_column('pr_risk_assessment', 'llm_tokens_used', schema='pr_analysis')
    # ### end Alembic commands ###
