"""pr_analysis: initial tables

Revision ID: d3a90afebafe
Revises: 
Create Date: 2026-07-02 13:49:17.992898

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd3a90afebafe'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('pr_analysis',)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_flaky_signal_projection',
    sa.Column('test_identifier', sa.String(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('flakiness_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('test_identifier', 'repository'),
    schema='pr_analysis'
    )
    op.create_table('outbox_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='pr_analysis'
    )
    op.create_table('pull_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(), nullable=False),
    sa.Column('base_sha', sa.String(), nullable=False),
    sa.Column('author_login', sa.String(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pr_analysis'
    )
    op.create_table('pr_risk_assessment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pr_analysis.pull_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pr_analysis'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pr_risk_assessment', schema='pr_analysis')
    op.drop_table('pull_request', schema='pr_analysis')
    op.drop_table('outbox_event', schema='pr_analysis')
    op.drop_table('local_flaky_signal_projection', schema='pr_analysis')
    # ### end Alembic commands ###
