apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "sibyl.apiLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "sibyl.apiLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: {{ .Values.api.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    {{- include "sibyl.workerLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "sibyl.workerLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.worker.healthPort }}
      targetPort: {{ .Values.worker.healthPort }}
      name: metrics
