"""ingestion: initial tables

Revision ID: c472a822886c
Revises: 
Create Date: 2026-07-02 13:21:32.379622

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c472a822886c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('ingestion',)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion'
    )
    op.create_table('webhook_delivery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_delivery_id', sa.String(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_delivery_id'),
    schema='ingestion'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_delivery', schema='ingestion')
    op.drop_table('outbox_event', schema='ingestion')
    # ### end Alembic commands ###
