"""root_cause_analysis add llm latency tracking

Revision ID: 2f4c9d2856af
Revises: d4ae5c089488
Create Date: 2026-07-07 11:52:55.807393

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2f4c9d2856af'
down_revision: str | Sequence[str] | None = 'd4ae5c089488'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'root_cause_hypothesis',
        sa.Column('llm_latency_ms', sa.Integer(), nullable=False),
        schema='root_cause_analysis',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('root_cause_hypothesis', 'llm_latency_ms', schema='root_cause_analysis')
    # ### end Alembic commands ###
