"""root_cause_analysis: initial tables

Revision ID: d4ae5c089488
Revises: 
Create Date: 2026-07-02 15:49:11.908970

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd4ae5c089488'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('root_cause_analysis',)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('test_identifier', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('ci_run_id', sa.BigInteger(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository', 'test_identifier', 'commit_sha', 'ci_run_id'),
    schema='root_cause_analysis'
    )
    op.create_table('flaky_signal_projection',
    sa.Column('test_identifier', sa.String(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('flakiness_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('test_identifier', 'repository'),
    schema='root_cause_analysis'
    )
    op.create_table('outbox_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='root_cause_analysis'
    )
    op.create_table('pr_context_projection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('explanation_unavailable', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository', 'pr_number'),
    schema='root_cause_analysis'
    )
    op.create_table('test_impact_projection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('affected_tests', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository', 'pr_number'),
    schema='root_cause_analysis'
    )
    op.create_table('root_cause_hypothesis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('failure_event_id', sa.UUID(), nullable=False),
    sa.Column('hypothesis_text', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('suspected_commit_sha', sa.String(), nullable=True),
    sa.Column('suspected_file_path', sa.String(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['failure_event_id'], ['root_cause_analysis.failure_event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='root_cause_analysis'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('root_cause_hypothesis', schema='root_cause_analysis')
    op.drop_table('test_impact_projection', schema='root_cause_analysis')
    op.drop_table('pr_context_projection', schema='root_cause_analysis')
    op.drop_table('outbox_event', schema='root_cause_analysis')
    op.drop_table('flaky_signal_projection', schema='root_cause_analysis')
    op.drop_table('failure_event', schema='root_cause_analysis')
    # ### end Alembic commands ###
