"""identity: initial tables

Revision ID: 9c03755d37a9
Revises: 
Create Date: 2026-07-02 13:21:00.573348

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9c03755d37a9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('identity',)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_login', sa.String(), nullable=False),
    sa.Column('repository_selection', sa.String(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_installation_id'),
    schema='identity'
    )
    op.create_table('installation_repository',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('repository_full_name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['identity.installation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installation_repository', schema='identity')
    op.drop_table('installation', schema='identity')
    # ### end Alembic commands ###
